[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "willitjit"
version = "0.1.0"
description = "Test package compatibility with the experimental CPython JIT"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
license-files = ["LICENSE"]

[dependency-groups]
dev = [
    "packaging>=25.0",
    "prek>=0.4.14",
]

[project.scripts]
willitjit = "willitjit.cli:main"
